tft:
  - name: "Test 1"
    namespace: "default"
    test_cases: "1"
    duration: "10"
    connections:
      - name: "Connection 1"
        type: "iperf"
        instances: 1
        server:
          - name: "worker-229"
            persistent: "false"
            type: "sriov"
        client:
          - name: "worker-230"
            type: "sriov"
        plugins:
          - name: capture_flows
          - name: measure_cpu
          - name: measure_power
