tft:
  - name: "Test 1"
    namespace: "default"
    test_cases: "1"
    duration: "10"
    connections:
      - name: "Connection 1"
        type: "iperf-tcp"
        # type: "iperf-udp"
        # type: "http"
        instances: 1
        server:
          - name: "worker-229"
            persistent: "false"
            sriov: "true"
        client:
          - name: "worker-230"
            sriov: "true"
        plugins:
          - name: capture_flows
          - name: measure_cpu
          - name: measure_power
