name: Build and Push

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      run: |
        docker buildx create --use

    - name: Convert GitHub repository owner to lowercase
      id: lowercase_owner
      run: echo "owner=$(echo '${{ github.repository_owner }}' | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

    - name: Log in to GitHub Container Registry
      run: |
        echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

    - name: Build and Push Multiarch Image to ghcr.io
      run: |
        docker buildx build \
          --file ./Containerfile \
          --platform linux/arm64,linux/amd64 \
          --tag ghcr.io/${{ env.owner }}/ocp-traffic-flow-tests:latest \
          --push \
          .
