name: Check style, test

on:
  push:
    branches:
  pull_request:
    branches:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install black mypy pytest
        python -m pip install -r requirements.txt
        python -m pip install flake8
        python -m pip install types-PyYAML
        python -m pip install jc
    - name: Check code formatting with Black
      run: |
       black --version
       black --check --diff .
    - name: flake8
      run: |
       flake8 --version
       flake8
    - name: Type check with Mypy
      run: |
       mypy --version
       mypy --strict --config-file mypy.ini .
    - name: Run tests with Pytest
      run: | 
       pytest --version
       pytest
